<?php

namespace App\Http\Requests\Child;

use Illuminate\Foundation\Http\FormRequest;
use App\Models\ContactBook;

class ContactBook0SchoolRequest extends FormRequest {

    public function rules() {
        return [
            'date'              =>  ['required', 'date_format:Y-m-d'],
            'weather'           =>  ['nullable', 'string'],
            'mood'              =>  ['nullable', 'in:0,1,2,3'],
            // 'pick_up_person'    =>  ['nullable', 'string'],
            // 'pick_up_time'      =>  ['nullable', 'date_format:H:i'],
            'nurse_name'        =>  ['nullable', 'string'],
            // 'temperature_time_std'  =>  ['nullable', 'date_format:H:i'],
            // 'temperature_std'   =>  ['nullable', 'numeric'],
            'guardian'          =>  ['nullable', 'string'],
            'status'            =>  ['nullable', 'in:' . ContactBook::STATUS_TEMPORARY . ',' . ContactBook::STATUS_COMPLETED],
            'sleep_0100_school' =>  ['nullable', 'boolean'],
            'sleep_0130_school' =>  ['nullable', 'boolean'],
            'sleep_0200_school' =>  ['nullable', 'boolean'],
            'sleep_0230_school' =>  ['nullable', 'boolean'],
            'sleep_0300_school' =>  ['nullable', 'boolean'],
            'sleep_0330_school' =>  ['nullable', 'boolean'],
            'sleep_0400_school' =>  ['nullable', 'boolean'],
            'sleep_0430_school' =>  ['nullable', 'boolean'],
            'sleep_0500_school' =>  ['nullable', 'boolean'],
            'sleep_0530_school' =>  ['nullable', 'boolean'],
            'sleep_0600_school' =>  ['nullable', 'boolean'],
            'sleep_0630_school' =>  ['nullable', 'boolean'],
            'sleep_0700_school' =>  ['nullable', 'boolean'],
            'sleep_0730_school' =>  ['nullable', 'boolean'],
            'sleep_0800_school' =>  ['nullable', 'boolean'],
            'sleep_0830_school' =>  ['nullable', 'boolean'],
            'sleep_0900_school' =>  ['nullable', 'boolean'],
            'sleep_0930_school' =>  ['nullable', 'boolean'],
            'sleep_1000_school' =>  ['nullable', 'boolean'],
            'sleep_1030_school' =>  ['nullable', 'boolean'],
            'sleep_1100_school' =>  ['nullable', 'boolean'],
            'sleep_1130_school' =>  ['nullable', 'boolean'],
            'sleep_1200_school' =>  ['nullable', 'boolean'],
            'sleep_1230_school' =>  ['nullable', 'boolean'],
            'sleep_0800_school' =>  ['nullable', 'boolean'],
            'sleep_0830_school' =>  ['nullable', 'boolean'],
            'sleep_0900_school' =>  ['nullable', 'boolean'],
            'sleep_0930_school' =>  ['nullable', 'boolean'],
            'sleep_1000_school' =>  ['nullable', 'boolean'],
            'sleep_1030_school' =>  ['nullable', 'boolean'],
            'sleep_1100_school' =>  ['nullable', 'boolean'],
            'sleep_1130_school' =>  ['nullable', 'boolean'],
            'sleep_1200_school' =>  ['nullable', 'boolean'],
            'sleep_1230_school' =>  ['nullable', 'boolean'],
            'sleep_1300_school' =>  ['nullable', 'boolean'],
            'sleep_1330_school' =>  ['nullable', 'boolean'],
            'sleep_1400_school' =>  ['nullable', 'boolean'],
            'sleep_1430_school' =>  ['nullable', 'boolean'],
            'sleep_1500_school' =>  ['nullable', 'boolean'],
            'sleep_1530_school' =>  ['nullable', 'boolean'],
            'sleep_1600_school' =>  ['nullable', 'boolean'],
            'sleep_1630_school' =>  ['nullable', 'boolean'],
            'sleep_1700_school' =>  ['nullable', 'boolean'],
            'sleep_1730_school' =>  ['nullable', 'boolean'],
            'sleep_1800_school' =>  ['nullable', 'boolean'],
            'sleep_1830_school' =>  ['nullable', 'boolean'],
            'sleep_1900_school' =>  ['nullable', 'boolean'],
            'sleep_1930_school' =>  ['nullable', 'boolean'],
            'sleep_2000_school' =>  ['nullable', 'boolean'],
            'sleep_2030_school' =>  ['nullable', 'boolean'],
            'sleep_2100_school' =>  ['nullable', 'boolean'],
            'sleep_2130_school' =>  ['nullable', 'boolean'],
            'sleep_2200_school' =>  ['nullable', 'boolean'],
            'sleep_2230_school' =>  ['nullable', 'boolean'],
            'sleep_2300_school' =>  ['nullable', 'boolean'],
            'sleep_2330_school' =>  ['nullable', 'boolean'],
            'sleep_2400_school' =>  ['nullable', 'boolean'],
            'sleep_2430_school' =>  ['nullable', 'boolean'],
            'temperature_01_school' =>  ['nullable', 'numeric'],
            'temperature_02_school' =>  ['nullable', 'numeric'],
            'temperature_03_school' =>  ['nullable', 'numeric'],
            'temperature_04_school' =>  ['nullable', 'numeric'],
            'temperature_05_school' =>  ['nullable', 'numeric'],
            'temperature_06_school' =>  ['nullable', 'numeric'],
            'temperature_07_school' =>  ['nullable', 'numeric'],
            'temperature_08_school' =>  ['nullable', 'numeric'],
            'temperature_09_school' =>  ['nullable', 'numeric'],
            'temperature_10_school' =>  ['nullable', 'numeric'],
            'temperature_11_school' =>  ['nullable', 'numeric'],
            'temperature_12_school' =>  ['nullable', 'numeric'],
            'temperature_13_school' =>  ['nullable', 'numeric'],
            'temperature_14_school' =>  ['nullable', 'numeric'],
            'temperature_15_school' =>  ['nullable', 'numeric'],
            'temperature_16_school' =>  ['nullable', 'numeric'],
            'temperature_17_school' =>  ['nullable', 'numeric'],
            'temperature_18_school' =>  ['nullable', 'numeric'],
            'temperature_19_school' =>  ['nullable', 'numeric'],
            'temperature_20_school' =>  ['nullable', 'numeric'],
            'temperature_21_school' =>  ['nullable', 'numeric'],
            'temperature_22_school' =>  ['nullable', 'numeric'],
            'temperature_23_school' =>  ['nullable', 'numeric'],
            'temperature_24_school' =>  ['nullable', 'numeric'],
            'defecation_1_school'   =>  ['nullable', 'in:0,1,2,3'],
            'defecation_2_school'   =>  ['nullable', 'in:0,1,2,3'],
            'defecation_3_school'   =>  ['nullable', 'in:0,1,2,3'],
            'defecation_4_school'   =>  ['nullable', 'in:0,1,2,3'],
            'defecation_5_school'   =>  ['nullable', 'in:0,1,2,3'],
            'defecation_6_school'   =>  ['nullable', 'in:0,1,2,3'],
            'defecation_7_school'   =>  ['nullable', 'in:0,1,2,3'],
            'defecation_8_school'   =>  ['nullable', 'in:0,1,2,3'],
            'defecation_9_school'   =>  ['nullable', 'in:0,1,2,3'],
            'defecation_10_school'  =>  ['nullable', 'in:0,1,2,3'],
            'defecation_11_school'  =>  ['nullable', 'in:0,1,2,3'],
            'defecation_12_school'  =>  ['nullable', 'in:0,1,2,3'],
            'defecation_13_school'  =>  ['nullable', 'in:0,1,2,3'],
            'defecation_14_school'  =>  ['nullable', 'in:0,1,2,3'],
            'defecation_15_school'  =>  ['nullable', 'in:0,1,2,3'],
            'defecation_16_school'  =>  ['nullable', 'in:0,1,2,3'],
            'defecation_17_school'  =>  ['nullable', 'in:0,1,2,3'],
            'defecation_18_school'  =>  ['nullable', 'in:0,1,2,3'],
            'defecation_19_school'  =>  ['nullable', 'in:0,1,2,3'],
            'defecation_20_school'  =>  ['nullable', 'in:0,1,2,3'],
            'defecation_21_school'  =>  ['nullable', 'in:0,1,2,3'],
            'defecation_22_school'  =>  ['nullable', 'in:0,1,2,3'],
            'defecation_23_school'  =>  ['nullable', 'in:0,1,2,3'],
            'defecation_24_school'  =>  ['nullable', 'in:0,1,2,3'],
            'meal_1_school'     =>  ['nullable', 'string'],
            'meal_2_school'     =>  ['nullable', 'string'],
            'meal_3_school'     =>  ['nullable', 'string'],
            'meal_4_school'     =>  ['nullable', 'string'],
            'meal_5_school'     =>  ['nullable', 'string'],
            'meal_6_school'     =>  ['nullable', 'string'],
            'meal_7_school'     =>  ['nullable', 'string'],
            'meal_8_school'     =>  ['nullable', 'string'],
            'meal_9_school'     =>  ['nullable', 'string'],
            'meal_10_school'    =>  ['nullable', 'string'],
            'meal_11_school'    =>  ['nullable', 'string'],
            'meal_12_school'    =>  ['nullable', 'string'],
            'meal_13_school'    =>  ['nullable', 'string'],
            'meal_14_school'    =>  ['nullable', 'string'],
            'meal_15_school'    =>  ['nullable', 'string'],
            'meal_16_school'    =>  ['nullable', 'string'],
            'meal_17_school'    =>  ['nullable', 'string'],
            'meal_18_school'    =>  ['nullable', 'string'],
            'meal_19_school'    =>  ['nullable', 'string'],
            'meal_20_school'    =>  ['nullable', 'string'],
            'meal_21_school'    =>  ['nullable', 'string'],
            'meal_22_school'    =>  ['nullable', 'string'],
            'meal_23_school'    =>  ['nullable', 'string'],
            'meal_24_school'    =>  ['nullable', 'string'],
            'state_0_school'    =>  ['nullable', 'string'],
            'contact_0_school'  =>  ['nullable', 'string'],

        ];
    }
}
